{
 "title": "New dashboard",
 "time": { "from": "2024-07-28T17:58:17.578Z", "to": "2024-07-28T18:22:17.578Z" },
 "panels": [
  {
   "title": "cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ram",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (windows_memory_available_bytes / windows_cs_physical_memory_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network total Mbps",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_total{instance=\"localhost:9182\"}[1m]) / 1024 / 1024 *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk read mb/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{instance=\"localhost:9182\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{instance=\"localhost:9182\"}[5m])/ 1024 / 1024 * 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network sent ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(rate(windows_net_bytes_sent_total{instance=\"localhost:9182\"}[1m])) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(windows_net_bytes_sent_total{instance=\"localhost:9182\"}[1d])) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance=\"localhost:9182\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(windows_net_bytes_received_total{instance=\"localhost:9182\"}[1d])) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk write mb/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{instance=\"localhost:9182\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{instance=\"localhost:9182\"}[5m]) / 1024 / 1024 * 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "100 * (1 - (windows_memory_available_bytes / windows_cs_physical_memory_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((1 - (windows_memory_available_bytes / windows_cs_physical_memory_bytes))[12h:]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}